#!/bin/bash

# Script to reinstall all Flatpak applications
# Automatically generated by pre-push hook

echo "Starting Flatpak applications reinstallation..."

# Check and install com.brave.Browser
if ! flatpak list --app --columns=application | grep -q "^com.brave.Browser$"; then
  echo "Installing com.brave.Browser..."
  flatpak install flathub com.brave.Browser -y
else
  echo "com.brave.Browser is already installed, skipping..."
fi

# Check and install com.dec05eba.gpu_screen_recorder
if ! flatpak list --app --columns=application | grep -q "^com.dec05eba.gpu_screen_recorder$"; then
  echo "Installing com.dec05eba.gpu_screen_recorder..."
  flatpak install flathub com.dec05eba.gpu_screen_recorder -y
else
  echo "com.dec05eba.gpu_screen_recorder is already installed, skipping..."
fi

# Check and install com.discordapp.Discord
if ! flatpak list --app --columns=application | grep -q "^com.discordapp.Discord$"; then
  echo "Installing com.discordapp.Discord..."
  flatpak install flathub com.discordapp.Discord -y
else
  echo "com.discordapp.Discord is already installed, skipping..."
fi

# Check and install com.github.marinm.songrec
if ! flatpak list --app --columns=application | grep -q "^com.github.marinm.songrec$"; then
  echo "Installing com.github.marinm.songrec..."
  flatpak install flathub com.github.marinm.songrec -y
else
  echo "com.github.marinm.songrec is already installed, skipping..."
fi

# Check and install com.github.tchx84.Flatseal
if ! flatpak list --app --columns=application | grep -q "^com.github.tchx84.Flatseal$"; then
  echo "Installing com.github.tchx84.Flatseal..."
  flatpak install flathub com.github.tchx84.Flatseal -y
else
  echo "com.github.tchx84.Flatseal is already installed, skipping..."
fi

# Check and install io.freetubeapp.FreeTube
if ! flatpak list --app --columns=application | grep -q "^io.freetubeapp.FreeTube$"; then
  echo "Installing io.freetubeapp.FreeTube..."
  flatpak install flathub io.freetubeapp.FreeTube -y
else
  echo "io.freetubeapp.FreeTube is already installed, skipping..."
fi

# Check and install org.kde.kdenlive
if ! flatpak list --app --columns=application | grep -q "^org.kde.kdenlive$"; then
  echo "Installing org.kde.kdenlive..."
  flatpak install flathub org.kde.kdenlive -y
else
  echo "org.kde.kdenlive is already installed, skipping..."
fi

# Check and install org.keepassxc.KeePassXC
if ! flatpak list --app --columns=application | grep -q "^org.keepassxc.KeePassXC$"; then
  echo "Installing org.keepassxc.KeePassXC..."
  flatpak install flathub org.keepassxc.KeePassXC -y
else
  echo "org.keepassxc.KeePassXC is already installed, skipping..."
fi

# Check and install org.telegram.desktop
if ! flatpak list --app --columns=application | grep -q "^org.telegram.desktop$"; then
  echo "Installing org.telegram.desktop..."
  flatpak install flathub org.telegram.desktop -y
else
  echo "org.telegram.desktop is already installed, skipping..."
fi

echo "Flatpak applications reinstallation completed!"
